apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJZWGRyY3pnNE9tZG9jRjlCVkhkblprTkxjblZJZDFnNWIwTTVZMnN4VG5ock1qZHBaMU5vZVRJd1RVUnJXRlU9IgoJCX0sCgkJImh0dHBzOi8vcmVnaXN0cnkuZ2l0bGFiLmNvbSI6IHt9LAoJCSJyZWdpc3RyeS5naXRsYWIuY29tIjoge30sCgkJInJlZ2lzdHJ5Lmhlcm9rdS5jb20iOiB7fQoJfSwKCSJjdXJyZW50Q29udGV4dCI6ICJjb2xpbWEiCn0=
type: kubernetes.io/dockerconfigjson
